t

diff --git a/.github/workflows/grade.yml b/.github/workflows/grade.yml
--- a/.github/workflows/grade.yml
+++ b/.github/workflows/grade.yml
@@ -23,12 +23,15 @@ jobs:
           curl -s https://raw.githubusercontent.com/ViMaSter/github-starter-course-test/main/README.md > README.md
           echo "after curl"
           cat README.md
-          # run git diff but don't exit on error but capture exit code
-          exit_code=0
-          git diff --exit-code || exit_code=$?
-          echo "git diff exit code: $exit_code"
-          if [ $exit_code -eq 0 ]; then
-            exit 1
-          else
+          # capture exit code of git diff --exit-code
+          git diff --exit-code
+          # if 1 exit with 0 if 0 exit with 1
+          if [ $? -eq 1 ]; then
+            echo "git diff found changes"
             exit 0
+          else
+            echo "git diff found no changes"
+            exit 1
           fi
+          
+t
